version: '3'

services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
    # credentials DB, please verify
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: anoc_db

    volumes:
      - ./postgres-data:/var/lib/postgresql/data